CREATE TABLE `boomerangdb`.`users` (
  `userid` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(60) NOT NULL,
  `lastName` VARCHAR(45) NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) GENERATED ALWAYS AS ((CONCAT(lastName,'-',firstName))) VIRTUAL,
  `street` VARCHAR(60) NOT NULL,
  `suburb` VARCHAR(60) NOT NULL,
  `state` VARCHAR(60) NOT NULL,
  `country` VARCHAR(45) NOT NULL DEFAULT 'Australia',
  `postCode` SMALLINT(4) NOT NULL,
  `dateJoined` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` VARCHAR(20) NOT NULL,
  `userType` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userid`),
  UNIQUE INDEX `userid_UNIQUE` (`userid` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE);
